In [1]:
%pylab
%matplotlib inline
import tensorflow as tf

Using matplotlib backend: Qt4Agg
Populating the interactive namespace from numpy and matplotlib


In [4]:
np.loadtxt?

In [8]:
xy = np.loadtxt('./train.txt', unpack=True, dtype='float32', delimiter=',')
x_data = np.transpose(xy[0:3])
y_data = np.transpose(xy[3:])

#tf graph input
X = tf.placeholder('float', [None, 3]) #x1, x2 and 1 (for bias)
Y = tf.placeholder('float', [None, 3]) #A, B, C => 3 classes
# Set model weights
W = tf.Variable(tf.zeros([3, 3]))

# Construct model
hypothesis = tf.nn.softmax(tf.matmul(X, W)) # Softmax

# minimize error using cross entropy
learning_rate = 0.001

# Cross entropy
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), reduction_indices=1))

#gradient Descent
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

#Initializing the variables
init = tf.initialize_all_variables()

# Launch the graph
with tf.Session() as sess:
    sess.run(init)
    
    for step in xrange(2001):
        sess.run(optimizer, feed_dict={X:x_data, Y:y_data})
        if step %200 == 0:
            print step, sess.run(cost, feed_dict={X:x_data, Y:y_data}), sess.run(W)

0 1.09774 [[ -8.33333252e-05   4.16666626e-05   4.16666480e-05]
 [  1.66666694e-04   2.91666773e-04  -4.58333408e-04]
 [  1.66666636e-04   4.16666706e-04  -5.83333429e-04]]
200 1.05962 [[-0.02051384 -0.00103983  0.02155367]
 [ 0.01406439  0.01097753 -0.0250419 ]
 [ 0.01431208  0.03574874 -0.05006079]]
400 1.04985 [[-0.04282598 -0.00625899  0.04908497]
 [ 0.01747187  0.00156368 -0.01903554]
 [ 0.01831204  0.04954104 -0.06785305]]
600 1.0407 [[-0.06517859 -0.01176361  0.07694223]
 [ 0.01943521 -0.00848972 -0.01094547]
 [ 0.0211558   0.06118308 -0.0823388 ]]
800 1.03194 [[-0.08734013 -0.01729389  0.10463406]
 [ 0.0211172  -0.01796171 -0.00315547]
 [ 0.02396628  0.07198346 -0.09594975]]
1000 1.02354 [[-0.10928574 -0.02282182  0.13210759]
 [ 0.02266255 -0.02678035  0.00411784]
 [ 0.02685851  0.08210357 -0.10896213]]
1200 1.01547 [[-0.13101467 -0.02834093  0.15935563]
 [ 0.02409704 -0.03497621  0.01087924]
 [ 0.02983199  0.091598   -0.12143002]]
1400 1.0077 [[-0.15252906 -0.03384716  0.18637

In [12]:
xy = np.loadtxt('./train.txt', unpack=True, dtype='float32', delimiter=',')
x_data = np.transpose(xy[0:3])
y_data = np.transpose(xy[3:])

#tf graph input
X = tf.placeholder('float', [None, 3]) #x1, x2 and 1 (for bias)
Y = tf.placeholder('float', [None, 3]) #A, B, C => 3 classes
# Set model weights
W = tf.Variable(tf.zeros([3, 3]))

# Construct model
hypothesis = tf.nn.softmax(tf.matmul(X, W)) # Softmax

# minimize error using cross entropy
learning_rate = 0.001

# Cross entropy
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), reduction_indices=1))

#gradient Descent
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

#Initializing the variables
init = tf.initialize_all_variables()

# Launch the graph
with tf.Session() as sess:
    sess.run(init)
    
    for step in xrange(2001):
        sess.run(optimizer, feed_dict={X:x_data, Y:y_data})
        #if step %200 == 0:
        #    print step, sess.run(cost, feed_dict={X:x_data, Y:y_data}), sess.run(W)


    a = sess.run(hypothesis, feed_dict={X:[[1, 11, 7]]})
    print a, sess.run(tf.arg_max(a, 1))

    b = sess.run(hypothesis, feed_dict={X:[[1, 3, 4]]})
    print b, sess.run(tf.arg_max(b, 1))

    all = sess.run(hypothesis, feed_dict={X:[[1, 11, 7], [1, 3, 4], [1, 1, 0]]})
    print all, sess.run(tf.arg_max(all, 1))

 [[ 0.46272627  0.35483009  0.18244369]] [0]
[[ 0.33820099  0.42101383  0.24078514]] [1]
[[ 0.46272627  0.35483006  0.18244369]
 [ 0.33820099  0.42101383  0.24078514]
 [ 0.27002314  0.29085544  0.4391214 ]] [0 1 2]
